# Generated by Django 5.0.4 on 2024-08-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('nome', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cadastro_usuario_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('quantidade_usuario', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('administradores', models.IntegerField()),
                ('grupo_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('quantidade_livros', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('genero', models.TextField()),
                ('editora', models.TextField()),
                ('autor', models.TextField()),
                ('titulo_livro', models.TextField()),
                ('pesquisa_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('texto_resenha', models.CharField(max_length=500)),
                ('nota_resenha', models.IntegerField()),
                ('titulo_resenha', models.CharField(max_length=100)),
                ('data_resenha', models.DateTimeField(auto_now_add=True)),
                ('id_resenha', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('genero', models.TextField()),
                ('sinopse', models.CharField(max_length=200)),
                ('quantidade_paginas', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('editora', models.TextField()),
                ('idioma', models.TextField()),
                ('classificacao_indicativa', models.TextField()),
                ('resenhas', models.IntegerField()),
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('resenha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.resenha')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=100)),
                ('lendo_atualmente', models.IntegerField()),
                ('pretende_ler', models.IntegerField()),
                ('lidos', models.IntegerField()),
                ('favoritos', models.IntegerField()),
                ('quantidade_seguidores', models.IntegerField()),
                ('quantidade_seguindo', models.IntegerField()),
                ('imagem_perfil', models.ImageField(upload_to='')),
                ('resenhas_usuario', models.IntegerField()),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.cadastro')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.grupo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.lista')),
                ('resenha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.resenha')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_has_Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.pesquisa')),
                ('resenha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.resenha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.usuario')),
            ],
        ),
    ]
