# Generated by Django 5.0.4 on 2024-08-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('frase', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
