# Generated by Django 5.0.4 on 2025-01-10 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0002_statusleitura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interacaolivro',
            unique_together={('livro', 'usuario')},
        ),
        migrations.AddField(
            model_name='interacaolivro',
            name='data_interacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interacaolivro',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas_site.livro'),
        ),
        migrations.AlterField(
            model_name='interacaolivro',
            name='status',
            field=models.CharField(choices=[('lido', 'Lido'), ('quero_ler', 'Quero Ler'), ('larguei', 'Larguei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='interacaolivro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='interacaolivro',
            name='favorito',
        ),
    ]
