# Generated by Django 5.0.4 on 2025-01-10 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0003_alter_interacaolivro_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacaolivro',
            name='data_interacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
