# Generated by Django 5.0.4 on 2024-10-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0006_alter_livro_data_publicacao_alter_livro_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(),
        ),
    ]
