# Generated by Django 5.0.4 on 2024-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0007_alter_livro_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='bio_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='foto_autor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
