# Generated by Django 5.0.4 on 2025-01-25 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0007_alter_resenha_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='livro',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to='telas_site.livro'),
        ),
    ]
