# Generated by Django 5.0.4 on 2024-10-17 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0008_livro_bio_autor_livro_foto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='id_livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to='telas_site.livro'),
        ),
    ]
