# Generated by Django 5.0.4 on 2024-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0009_resenha_id_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
