# Generated by Django 5.0.4 on 2025-01-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0009_alter_resenha_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagens/'),
        ),
    ]
