# Generated by Django 5.0.4 on 2024-10-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0010_resenha_foto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='telas_site.usuario'),
        ),
    ]
