# Generated by Django 5.0.4 on 2024-10-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0011_resenha_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='nota_resenha',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
