# Generated by Django 5.0.4 on 2024-10-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0014_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lendo_atualmente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
