# Generated by Django 5.0.4 on 2024-10-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0015_alter_usuario_lendo_atualmente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pretende_ler',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='quantidade_seguidores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='quantidade_seguindo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='resenhas_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
