# Generated by Django 5.0.4 on 2024-10-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0016_alter_usuario_favoritos_alter_usuario_imagem_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resenha',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='resenha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenhas', to='telas_site.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='resenha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='telas_site.resenha'),
        ),
    ]
