# Generated by Django 5.0.4 on 2024-10-18 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas_site', '0020_alter_usuario_grupo_alter_usuario_lista_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='resenha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='resenha',
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telas_site.grupo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telas_site.lista'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
